# HappyHud by Ehhthan

# If the default files should be generated.
generate-default-files: true

# If the unicode text files should be generated.
generate-unicode-files: true

# If old shaders should be allowed to regenerate. Do not disable this unless you know what you're doing.
allow-shader-update: true

layout:
  # The layouts that every user starts with.
  default:
    - 'default-layout'

# The default value for how often placeholders should check for an update.
check-update: 5

# The way that numbers are displayed.
decimal-format: '#.##'

# If you would like to copy the built-resource pack to a different location.
copy-resource-pack:
  enabled: true
  # The location to copy each namespace to. The parent path is your plugins directory.
  namespaces:
    minecraft: "ItemsAdder/contents"
    happyhud: "ItemsAdder/contents"

boss-bar:
  # The maximum amount of shown boss bars a player can hold.
  max: 7
  # Which bossbar the huds display on.
  hud-position: 4
  color: yellow

# Disable the huds for any players connected through geyser.
disable-geyser-players: true

# Do not change this.
config-version: 6